### ISSUE TITLE
`Error getting container metrics: json: unsupported value: NaN` and have some high CPU usage spikes with COolify

### ISSUE THREAD

**Issue by MatteoGauthier** [coollabsio/sentinel#4] opened 2024-06-26 23:07 UTC
On my coolify instance, i've enabled Sentinel and I noticed high CPU usages spikes and lots of error logs for the sentinel container

![Capture d’écran 2024-06-27 à 01 03 59](https://github.com/coollabsio/sentinel/assets/32040951/e08aca50-b23d-414e-b366-8d85c23e7281)

**Comment by livghit** [comment] 2024-07-05 07:05
Hey , I've inspected the code a bit and noticed this one happen in the getOneContainerMetrics func
```go
func getOneContainerMetrics(containerID string, csv bool) (string, error) {
	ctx := context.Background()
	apiClient, err := client.NewClientWithOpts()
	if err != nil {
		return "", err
	}
	apiClient.NegotiateAPIVersion(ctx)
	defer apiClient.Close()
	metrics := ContainerMetrics{
		CPUUsagePercentage:    0,
		MemoryUsagePercentage: 0,
		MemoryUsed:            0,
		MemoryAvailable:       0,
		NetworkUsage:          NetworkDevice{},
	}
	container, err := apiClient.ContainerInspect(ctx, containerID)
	if err != nil {
		return "", err
	}
	stats, err := apiClient.ContainerStats(ctx, container.ID, false)
	if err != nil {
		return "", err
	}
	var v types.StatsJSON
	dec := json.NewDecoder(stats.Body)
	if err := dec.Decode(&v); err != nil {
		if err != io.EOF {
			fmt.Printf("Error decoding container stats: %v\n", err)
		}
	}
	defer stats.Body.Close()
	network_devices := v.Networks
	for _, device := range network_devices {
		metrics.NetworkUsage = NetworkDevice{
			Name:    device.InstanceID,
			RxBytes: device.RxBytes,
			TxBytes: device.TxBytes,
		}
	}

	metrics = ContainerMetrics{
		Time:                  getUnixTimeInMilliUTC(),
		CPUUsagePercentage:    calculateCPUPercent(v),
		MemoryUsagePercentage: calculateMemoryPercent(v),
		MemoryUsed:            calculateMemoryUsed(v),
		MemoryAvailable:       v.MemoryStats.Limit,
		NetworkUsage:          metrics.NetworkUsage,
	}
	jsonData, err := json.MarshalIndent(metrics, "", "    ")
	if err != nil {
		return "", err
	}
	if csv {
		return fmt.Sprintf("%s,%f,%d,%f\n", metrics.Time, metrics.CPUUsagePercentage, metrics.MemoryUsed, metrics.MemoryUsagePercentage), nil
	}
	return string(jsonData), nil
}
```

I think one of the calculation may be the reason this happen , but I am not sure . 
```go
metrics = ContainerMetrics{
		Time:                  getUnixTimeInMilliUTC(),
		CPUUsagePercentage:    calculateCPUPercent(v),
		MemoryUsagePercentage: calculateMemoryPercent(v),
		MemoryUsed:            calculateMemoryUsed(v),
		MemoryAvailable:       v.MemoryStats.Limit,
		NetworkUsage:          metrics.NetworkUsage,
	}
```

**Comment by livghit** [comment] 2024-07-05 16:14
Tested the whole thing locally and inside docker . I wasn't able to reproduce you're error .... 🥲

**Comment by mutonby** [comment] 2024-07-08 15:14
I have the same error, can it be deactivated or something?
![Captura de pantalla 2024-07-08 a las 14 15 04](https://github.com/coollabsio/sentinel/assets/30499505/6718345f-06cb-4207-8b06-04d9434b00f9)

**Comment by andrasbacsai** [comment] 2024-07-12 13:15
In coolify v312, I disabled Sentinel on all servers until this bug (and a few others) are not fixed.

**Comment by andrasbacsai** [comment] 2024-10-21 21:24
I changed everything in the next version (rewritten from 0), so this won't be an issue (also closing this).

**Closed by andrasbacsai** 2024-10-21 21:24 UTC
